# Generated by Django 4.1.5 on 2023-02-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=250)),
                ('img2', models.ImageField(upload_to='pics')),
                ('desc2', models.TextField()),
            ],
        ),
    ]
